### ISSUE TITLE
Why you create your own cnv instead of using  tf.nn.conv2d ?

### ISSUE THREAD

**Issue by a7744hsc** [guerzh/tf_weights#2]
Hi guerzh, I'm trying to learn tensorflow from your project, but I am confused when found out that you write a conv method yourself instead of using a buildin one in `myalexnet.py`. Could you please explain a little bit about this? 

ps: I open a issue because this is the only way I know to communicate with you.

**Comment by guerzh** [comment]
This has to do with the architecture of AlexNet, where there are two separate "columns" (originally, so that the processing could be done on two GPUs in parallel.) See e.g. here:

http://vision.stanford.edu/teaching/cs231b_spring1415/slides/alexnet_tugce_kyunghee.pdf (slide 15)

**Comment by a7744hsc** [comment]
Thanks for your reply @guerzh
