### ISSUE TITLE
Only giving Top 1 accuracy of 30% on Validation set

### ISSUE THREAD

**Issue by geevi** [guerzh/tf_weights#3]
Hi,
On feeding in the validation data of imagenet, it is only giving top 1 accuracy of 30% while the claimed accuracy of alexnet is 56%.

thanks for any help!

**Comment by guerzh** [comment]
Yes, that is unfortunately an issue (I made this code quickly for teaching purposes.) I don't know what's going wrong there.

**Comment by cyr6** [comment]
I think you forgot to implement the Dropout layer after each Decision layer. It might be the cause

**Comment by guerzh** [comment]
Hopefully this is fixed, will updated in a few days once I run the new version on the full test set
