### ISSUE TITLE
Image size should be 224x224x3 and not 227x227x3

### ISSUE THREAD

**Issue by cyr6** [guerzh/tf_weights#4]
Just a minor issue, but if I'm not mistaken, according to the AlexNet paper, the initial batch size should be 224x224x3 (instead of 227x227x3)

**Comment by guerzh** [comment]
It's true enough that it says that in the paper, but see here: http://cs231n.github.io/convolutional-networks/ (search for "224"). 

The network here is the same as the one used in the Caffe framework, with 227x227x3 inputs
