### ISSUE TITLE
Output of Classes Index and WNID

### ISSUE THREAD

**Issue by franciszchen** [guerzh/tf_weights#6]
Since Caffe offers caffe_ilsvrc_aux/train.txt as  a map from WNID to index 0-999, and ImageNet offers ILSVRC2012_devkit/data/meta.mat as a map from WNID to index 1-1000, and these two maps are different. Which does this project depend on?

**Comment by guerzh** [comment]
The Caffe indices. Note that I provide caffe_classes.py with the object names, which I generated using the caffe indices.
