### ISSUE TITLE
Last three layer not fc lays?

### ISSUE THREAD

**Issue by fengyuICT** [guerzh/tf_weights#7]
I check the caffe protext and see that alexnet has three fc layer, but is not seeing in your Graph struct? it's ok?

**Comment by guerzh** [comment]
Not sure what you mean -- there are three fc layers there -- look for fc6, fc7, fc8

**Comment by fengyuICT** [comment]
`#fc6
#fc(4096, name='fc6')
fc6W = tf.Variable(net_data["fc6"][0])
fc6b = tf.Variable(net_data["fc6"][1])
fc6 = tf.nn.relu_layer(tf.reshape(maxpool5, [-1, int(prod(maxpool5.get_shape()[1:]))]), fc6W, fc6b)

#fc7
#fc(4096, name='fc7')
fc7W = tf.Variable(net_data["fc7"][0])
fc7b = tf.Variable(net_data["fc7"][1])
fc7 = tf.nn.relu_layer(fc6, fc7W, fc7b)

#fc8
#fc(1000, relu=False, name='fc8')
fc8W = tf.Variable(net_data["fc8"][0])
fc8b = tf.Variable(net_data["fc8"][1])
fc8 = tf.nn.xw_plus_b(fc7, fc8W, fc8b)`
only fc8 use Mtrix multiply, but fc6 and fc7 is not use xw_plus_b. so my questions is why don't you use fc op to implment fc6 and fc7?

**Comment by guerzh** [comment]
https://www.tensorflow.org/api_docs/python/tf/nn/relu_layer is a fully connected layer + the ReLU activation

**Comment by fengyuICT** [comment]
thaks a lot
